### ISSUE TITLE
Transform data to CSV

### ISSUE THREAD

**Issue by peterdesmet** [enram/infrastructure#3]
### Do we really need to build this? And if so, how do we keep it simple?

I think CSVs are the most understandable and consumable format for everyone. We don't need to transform if the bird algorithm would directly output the data as CSV, but from what I understood: 1) HDF5 allows to also embed metadata and is thus better as a archive format 2) HDF5 is the default format used on BALTRAD?

### Questions

* [ ] @leijnse @adokter can you send us an example HDF5 file that is the output of the bird algorithm?
* [ ] @stijnvanhoey or @bartaelterman can you test https://github.com/h5py/h5py to transform the data to CSV?
* [ ] Once we can read an transform the file, we need to define what columns should be included in the CSV file.

**Comment by adokter** [comment]
Hi Peter,

I uploaded an example hdf5 bird profile file with an obsolete structure. The new format will look like [this](https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification)

**Comment by adokter** [comment]
I'm not convinced we need to convert hdf5 to csv. My preference would be to load hdf5 files directly into a relational database, and not provide access to a directory tree of CSVs.

**Comment by peterdesmet** [comment]
@adokter, we've come to similar conclusions. I'll remove the work package and close this issue.

**Comment by amirhouieh** [comment]
Hi, I have been looking for birds migration, for a visualisation project. While this data repository sounds the most reliable source, but it is almost impossible to get a hand on its data (particularly reading the data and not accessing it). I bet you have your reasons to use HDF5 and I respect it, but I think if you want to make this data available to more people, you should consider either presenting it in a more regular format (such as JSON, CSV, SQL, ...) or at least give a better and more explanatory insight of data structure. 
I have made a crawler which download the latest .h5 file of each Radar from S3, but now I have serious problem and in order to just parse this data I have to change my entire code-base ecosystem (from Java/Kotlin to python). Even assuming I am ok with doing this, I still have no idea for example what the parsed data represents.
I would appreciate if you can point me to some documentation where I can understand the data structure. A use-case for me would be for example `migration flow of specie X in country X at month 3`.

**Comment by stijnvanhoey** [comment]
With respect to the HDF5 data format, this is a community agreed [ODIM bird profile format specification](https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification) on which further study/visualisations/... can be built. 

Functionalities for data access, plotting and data analysis based on the S3 repository is supported by the [BioRad R package](https://github.com/adokter/bioRad). The [manuals of the package](http://adriaandokter.com/bioRad/articles/intro_vp.html) (called vignettes in the R worls) do explain how to use the package to download, process and visualize the data. Another source, is the [vp-processing](https://enram.github.io/vp-processing/index.html) manual written by @peterdesmet. He can also tell you more about the [existing migration visualisation](https://github.com/enram/bird-migration-flow-visualization).

At the same time, @adokter is currently submitting a paper about the BioRad package wich will provide more scientific background and are we refactoring the BioRad package (discussed mainly on [this issue](https://github.com/adokter/bioRad/issues/84); I'm currently doing the conversions of the package in the [rename-functions](https://github.com/adokter/bioRad/tree/rename_functions) branch). Notice that the current manuals and tutorials will be outdated (using deprecated functions of the package), but we try to get it all integrated in the package in the coming weeks/months.

**Comment by peterdesmet** [comment]
@amirhouieh in addition to @stijnvanhoey comment: are you looking to visualize bird migration data derived from _weather radars_ specifically or bird migration data in general? If the latter, then GPS tracking data might be more straightforward to visualize, e.g. https://doi.org/10.15468/02omly

**Comment by amirhouieh** [comment]
@stijnvanhoey thanks for the reply, I understand. 
@peterdesmet I am looking for bird migration in general. Thanks for the link, will look into it.
