### ISSUE TITLE
Extract and store settings data

### ISSUE THREAD

**Issue by peterdesmet** [enram/infrastructure#7]
### Do we really need to build this? And if so, how do we keep it simple?

@leijnse from what I understood in the meeting, it would be nice to extract and record the radar + bird algorithm settings used to generate the data. That data can change over time and is recorded in the HDF5 format. That is potentially challenging, so: how necessary is this? Is this information you can easily retrieve in another way? How many users are interested in this information?

**Comment by adokter** [comment]
Scientists will need this information, because we are and will be for a considerable time in a development phase, where there is no such thing as the perfect processing tool yet. Therefore I think for the years to come we need the information on algorithm and radar settings. We will likely end up in a situation where the same radar data will be processed in different ways, or that data will be re-run with updated algorithm settings.

**Comment by peterdesmet** [comment]
Ok, if you rerun, do we want to keep data from an old run or only the most recent version? And if you want to keep it, only the archived data (h5) or versioned in the database as well. It could increase the complexity a lot.

**Comment by adokter** [comment]
I would say: keep it simple for now and replace old data with reprocessed data.

**Comment by peterdesmet** [comment]
Great!
